# Generated by Django 4.2.7 on 2023-11-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_empresamodel_profissao_empresamodel_nuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatomodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='empresamodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
